-- 1. what is revenue generated by each gender

select gender, sum(Purchase_Amount) revenue_by_gender
from customer_info
group by gender


-- 2. which costomers used a discount but still spend more than average purchase amount?
select customer_id, Purchase_Amount as Purchase_Amount_more_avg
from customer_info
where Discount_Applied = 'Yes' 
		and Purchase_Amount >= (select avg(Purchase_Amount) from customer_info)


-- 3. which are the top 5 products with the highest average review rating?

select top 5
Item_Purchased, round(avg(review_rating),1) as avg_product_rating
from customer_info
group by Item_Purchased
order by avg(review_rating) desc


-- 4. compare the average purchase amounts between standand and express shipping.
select  Shipping_Type, round(avg(Purchase_Amount),1) as avg_amount_by_shipping_std_exp
from customer_info
where Shipping_Type in ('Standard','Express')
group by Shipping_Type

-- 5. do subscribed customerd spend more? campare average spend and total revenue between subscribers and non-subscribers.
select Subscription_Status, 
		count(customer_id) as total_customer_by_subscribe_status,
		avg(Purchase_Amount) as avg_spend_by_subscribe_status, 
		sum(purchase_amount) as total_revenue_by_subscribe_status
from  customer_info
group by Subscription_Status

-- 6. which 5 products have the highest percentage of purchase with discounts applied.

select top 5 
Item_Purchased, 
 round( 100 * sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*),2) as percentage_
from customer_info
group by Item_Purchased
order by percentage_ desc ;


-- 7. segment customer into new, returning, and loyal based on their total number of previous purchase and the count of each segment
with pp_segment as 
(select Customer_ID, Previous_Purchases,
		case when Previous_Purchases = 1 then 'new'
		when Previous_Purchases >= 2 and Previous_Purchases <= 10 then 'returning'
		else 'loyal'
		end as segments
from customer_info
)
select segments, count(Customer_ID) as pp_seg_count from pp_segment 
group by segments;


-- 8. what are the top 3 most purchased products within each category

select category, Item_Purchased, total_count 
from (select category, Item_Purchased, count(*) as total_count,
dense_rank() over(partition by category order by count(*) desc) rn
from customer_info
group by category, Item_Purchased) t
where rn <=3

-- 9. are customer who are repeat buyers (more tham 5 previous phurchase) also likely to subscribe?

select Subscription_Status, count(*)  as count_Subscription_Status
from customer_info
where Previous_Purchases > 5
group by Subscription_Status


-- 10. what is the revenue contribution of each age group

select age_category, sum(purchase_amount) as revenue_by_age 
from customer_info
group by age_category

